---
title: "Homework 2"
author: "jys2137"
date: "9/30/2021"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
```

The purpose of this file is to present the answers to Homework 2, an assignment reinforcing ideas in the **Data Wrangling I** topic for P8105. 


## Problem 0.1

This “problem” focuses on structure of my submission, especially the use git and GitHub for reproducibility, R Projects to organize my work, R Markdown to write reproducible reports, relative paths to load data from local files, and reasonable naming structures for my files.

To that end:

* I created a public GitHub repo + local R Project; we suggest naming this repo / directory p8105_hw2_jys2137
* I created a single .Rmd file named p8105_hw2_jys2137.Rmd that renders to github_document
* I created a subdirectory to store the local data files used in this assignment, and used relative paths to access these data files
* I will submit a link to my repo via Courseworks
* I aim to adhere to appropriate styling and clarity of code in Problems 1+.
